version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
        type = 'prompt'
        alignment = 'left'
        newline = true

        [[blocks.segments]]
                background = "#24a824"
                foreground = "#ffffff"
                style = "diamond"
                leading_diamond = ""
                trailing_diamond = ""
                template = "{{ if .WSL }}WSL at {{ end }}{{.Icon}} "
                type = "os"

        [[blocks.segments]]
                type = "session"
                style = "powerline"
                powerline_symbol = ""
                foreground = "#ffffff"
                background = "#2ed22e"
                template = " {{ if .SSHSession }} {{ end }}{{ .UserName }} "

        [[blocks.segments]]
                type = 'path'
                style = 'powerline'
                powerline_symbol = ""
                background = '#4e3b2b'
                foreground = '#ffffff'
                template = ' {{ .Path }} '

                [blocks.segments.properties]
                                style = 'full'

        [[blocks.segments]]
                type = "git"
                style = "powerline"
                powerline_symbol = ""
                foreground = "#193549"
                background = "#ffeb3b"
                background_templates = [
                        "{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}",
                        "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}",
                        "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
                        "{{ if gt .Behind 0 }}#B388FB{{ end }}"
                ]
                template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"

                [blocks.segments.properties]
                fetch_status = true
                fetch_upstream_icon = true
                source = "cli"

                        [blocks.segments.properties.untracked_modes]
                        "/Users/user/Projects/oh-my-posh/" = "no"

                        [blocks.segments.properties.mapped_branches]
                        "feature/*" = "🚀 "
                        "bugfix/*" = "🐛 "

        [[blocks.segments]]
                type = "lua"
                style = "powerline"
                powerline_symbol = ""
                foreground = "white"
                background = "blue"
                template = "  {{ .Full }} "

        [[blocks.segments]]
                type = "go"
                style = "powerline"
                powerline_symbol = ""
                foreground = "#ffffff"
                background = "#7FD5EA"
                template = "  {{ .Full }} "

        [[blocks.segments]]
                type = "python"
                style = "powerline"
                powerline_symbol = ""
                foreground = "#100e23"
                background = "#906cff"
                template = "  {{ .Full }} "

        [[blocks.segments]]
                type = "rust"
                style = "powerline"
                powerline_symbol = ""
                foreground = "#193549"
                background = "#99908a"
                template = "  {{ .Full }} "

[[blocks]]
  type = "rprompt"
  alignment = "right"

  [[blocks.segments]]
    type = "kubectl"
    style = "diamond"
    leading_diamond = "\ue0b6"
    trailing_diamond = "\ue0b4 "
    foreground = "#FFFFFF"
    background = "#326CE5"
    template = " ⎈ {{.Context}} "

  [[blocks.segments]]
    type = "time"
    style = "diamond"
    leading_diamond = "\ue0b6"
    template = " \ue641 {{ .CurrentDate | date .Format }} "
    background = "#003543"
    foreground = "#ffffff"

  [[blocks.segments]]
    type = "executiontime"
    style = "diamond"
    trailing_diamond = "\ue0b4"
    template = " \ueba2 {{ .FormattedMs }} "
    background = "#83769c"
    foreground = "#ffffff"

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

    [[blocks.segments]]
      type = 'text'
      style = 'plain'
      foreground_templates = [
        "{{if gt .Code 0}}red{{end}}",
        "{{if eq .Code 0}}green{{end}}",
      ]
      background = 'transparent'
      template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}green{{end}}",
  ]
  background = "transparent"
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '
