[manager]
show_hidden = true
show_symlink = true
linemode = "permissions_size_owner_mtime"
scrolloff = 5

[preview]
wrap = "yes"
image_quality = 90

[opener]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
 ]
